# Generated by Django 4.2.1 on 2023-05-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_room_roomformat_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='contact',
        ),
    ]
