# Generated by Django 4.2.1 on 2023-05-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_showtime_cinema_alter_showtime_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.roomformat'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.seatformat'),
        ),
    ]
