# Generated by Django 4.2.1 on 2023-05-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_seat_format_seat_seat_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatformat',
            name='price',
        ),
    ]
