# Generated by Django 4.2.1 on 2023-05-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_seatformat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[(1, 'action'), (2, 'adventure'), (3, 'comedy'), (4, 'drama'), (5, 'fantasy'), (6, 'horror'), (7, 'musicals'), (8, 'science fiction')], default=(2, 'adventure'), max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_format',
            field=models.CharField(choices=[(1, 'small'), (2, 'medium'), (3, 'big')], default=(2, 'medium'), max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(choices=[(1, '№1'), (2, '№2'), (3, '№3'), (4, '№4'), (5, '№5'), (6, '№6'), (7, '№7'), (8, '№8')], default=(2, '№2'), max_length=100),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
