# Generated by Django 4.2.1 on 2023-05-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_seat_row_alter_movie_genre_and_more'),
        ('tickets', '0012_remove_purchasehistory_ticket_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomFormat',
        ),
        migrations.DeleteModel(
            name='SeatFormat',
        ),
    ]
