# Generated by Django 4.2.1 on 2023-05-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_delete_roomformat_delete_seatformat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
