# Generated by Django 4.2.1 on 2023-05-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Visa-card'), (2, 'Klarna'), (3, 'MasterCard')], default=(2, 'Klarna'), max_length=100),
        ),
    ]
