# Generated by Django 4.2.1 on 2023-05-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_seat_row_alter_movie_genre_and_more'),
        ('tickets', '0011_remove_booking_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='ticket_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[(1, 'adult'), (2, 'student'), (3, 'child')], default=(2, 'student'), max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tickets.booking'),
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
