# Generated by Django 4.2.1 on 2023-05-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_booking_total_price_remove_ticket_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='movie',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_history', to='tickets.ticket'),
            preserve_default=False,
        ),
    ]
